import React, { useState } from "react";
import Head from "next/head";
import Breadcrumb from "./Breadcrumb";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";
import Script from "next/script";

const Layout = ({
  children,
  parent,
  sub,
  subChild,
  noBreadcrumb,
  headerStyle,
}) => {
  const [isToggled, setToggled] = useState(false);
  const toggleClick = () => {
    setToggled(!isToggled);
    isToggled
      ? document.querySelector("body").classList.remove("mobile-menu-active")
      : document.querySelector("body").classList.add("mobile-menu-active");
  };

  return (
    <>
      <Head>
        <title>FreshList Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDg8bRuV-VrBPOB2KOtMJ7mrGkD8trhoZM"></Script> */}

      {/* <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhNz0yWvFBAOb8IuaKiqzZo7eRqz7BCN4"></script> */}

      {/* <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script> */}

      <script
        type="text/javascript"
        src="https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=Museum%20of%20Contemporary%20Art%20Australia&inputtype=textquery&fields=photos,formatted_address,name,rating,opening_hours,geometry&key=AIzaSyDnDczEoeUwf7bN5b_-223uvrecPVfzggE"
      ></script>

      {isToggled && (
        <div className="body-overlay-1" onClick={toggleClick}></div>
      )}

      <Header
        headerStyle={headerStyle}
        isToggled={isToggled}
        toggleClick={toggleClick}
      />
      <MobileMenu isToggled={isToggled} toggleClick={toggleClick} />
      <main className="main">
        <Breadcrumb
          parent={parent}
          sub={sub}
          subChild={subChild}
          noBreadcrumb={noBreadcrumb}
        />
        {children}
      </main>

      <Footer />
    </>
  );
};

export default Layout;
